apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: testtuesapp-hpa
  labels:
    app: testtuesapp
    version: 0.0.1
    backstage.io/kubernetes-id: testtuesapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: testtuesapp
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75